name: CI
on: { push: { branches: [ main ] }, pull_request: {} }

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      PLAYWRIGHT_BASE_URL: http://localhost:3000
      MODEL_NAME: gpt-5
      LLM_FAKE: '1'
      STORAGE_MODE: 'memory'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: npx playwright install --with-deps

      - name: Build app
        run: pnpm build
      - name: Start app (background)
        run: |
          pnpm start & echo $! > .server.pid
          npx wait-on http://localhost:3000
      - name: Sanity ping
        run: curl -s http://localhost:3000 || true

      - name: API tests (Vitest)
        run: pnpm test:api
      - name: Enforce Vitest count
        run: pnpm check:vitest-count

      - name: UI tests (Playwright)
        run: pnpm test:ui
      - name: Enforce Playwright count
        run: pnpm check:pw-count

      - name: Stop server
        if: always()
        run: if [ -f .server.pid ]; then kill $(cat .server.pid) || true; fi


